model:
  hf_id: AIML-TUDA/LlavaGuard-v1.2-7B-OV-hf
  dtype: bfloat16
  device_map: auto
  prompt_template: llavaguard_default

extract:
  layers: [0, 2, 4]
  capture_point: post_attn_resid
  cross_attn_off_impl: zeros
  pooling:
    name: text_only_mean
    last_k: 5
  batch_size: 8
  num_workers: 4
  amp: true
  save:
    out_dir: artifacts/activations/llavaguard
    shard_size: 4000

data:
  datasets:
    - siuo_gen # memesafety_test # siuo_gen
  split: test
  root: datasets/SIUO/data # datasets/Meme-Safety-Bench/full # datasets/SIUO/data
  max_samples: null  # Limit samples for testing (remove or set to null for full dataset)

repro:
  seed: 42
