# Configuration for concept-based steering
model:
  hf_id: AIML-TUDA/LlavaGuard-v1.2-7B-OV-hf
  dtype: bfloat16
  device_map: auto

# GCAV steering configuration
steering:
  enabled: true
  cav_path: artifacts/cavs/concept_cavs.pkl
  target_layers: [20, 23, 25]  # Based on empirical findings for LLaVA models
  
  # Layer-specific configurations
  layer_20:
    target_prob: 0.3
    strength: 0.01
    direction: suppress
  
  layer_23:
    target_prob: 0.3
    strength: 0.01
    direction: suppress
    
  layer_25:
    target_prob: 0.3
    strength: 0.01
    direction: suppress

# Concept definitions
concepts:
  harmful_symbols:
    enabled: true
    direction: suppress
    strength: 0.01
    description: "Suppress harmful symbolic content"
  
  safe_content:
    enabled: true
    direction: amplify
    strength: 0.6
    description: "Amplify safe content responses"

# Data configuration for concept learning
data:
  samples: 200
  concept: "harmful_symbols"
  dataset_path: "datasets/hateful-memes"
  siuo_data_path: "datasets/SIUO/data"

# Output directories
output:
  activations_dir: "artifacts/activations"
  cavs_dir: "artifacts/cavs"
  visualizations_dir: "artifacts/visualizations"
  analysis_dir: "artifacts/analysis"
  results_dir: "results"

# CAV training parameters
training:
  test_size: 0.33
  regularization: 0.1
  max_iter: 1000
  random_state: 42

# Evaluation settings
evaluation:
  batch_size: 8
  max_new_tokens: 200
  temperature: 0.2
  top_p: 0.95
  metrics: ["safety_rate", "utility_score", "fluency_score"]

repro:
  seed: 42